<!DOCTYPE html>
<html lang="en-US">
<head>
    <?= $this->meta->head($index); ?>
</head>
<body>
    <h1>Canals</h1>
    <ul>
    <?php if($canals): ?>
        <?php foreach($canals as $canal): ?>
        <li><a href="<?= $canal->page ?>"><?= $canal->name ?></a></li>
        <?php endforeach; ?>
    <?php endif; ?>
    </ul>
    
    <?php if($pagination): ?>
        <ul>
            <?php foreach($pagination as $label => $link): ?>
            <li><a href="<?= $link ?>"><?= $label ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    
    <?= $this->meta->foot($index); ?>
</body>
</html>